# This is done except some of the extra keycloak cert bits
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tre.fullname" . }}-data-egress-ui
  labels:
    {{- include "tre.labels" . | nindent 4 }}
    component: "data-egress-ui"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tre.selectorLabels" . | nindent 6 }}
      component: "data-egress-ui"
  template:
    metadata:
      {{- with .Values.dataEgress.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tre.labels" . | nindent 8 }}
        component: "data-egress-ui"
        {{- with .Values.dataEgress.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tre.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tredataegressui
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.dataEgress.ui.image.repository }}:{{ .Values.dataEgress.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataEgress.ui.image.pullPolicy }}
          env:
            - name: Serilog__SeqServerUrl
              value: "{{ .Values.config.seqUrl }}"
            - name: DemoMode
              value: "{{ .Values.config.demoMode.enabled }}"
            - name: KeycloakDemoMode
              value: "{{ .Values.config.keycloakDemoMode }}"
            - name: DataEgressAPISettings__Address
              value: 'http://{{ include "tre.fullname" . }}-data-egress-api:{{ .Values.dataEgress.api.service.port }}'
            - name: DataEgressKeyCloakSettings__Authority
              value: "{{ default .Values.config.keycloak.dataEgress.api.authority .Values.config.keycloak.global.authority }}"
            - name: DataEgressKeyCloakSettings__MetadataAddress
              value: "{{ default .Values.config.keycloak.dataEgress.api.protocol .Values.config.keycloak.global.protocol }}://{{ default .Values.config.keycloak.dataEgress.api.host .Values.config.keycloak.global.host }}/realms/{{ .Values.config.keycloak.dataEgress.api.realm }}/.well-known/openid-configuration"
            - name: DataEgressKeyCloakSettings__BaseUrl
              value: "{{ default .Values.config.keycloak.dataEgress.api.protocol .Values.config.keycloak.global.protocol }}://{{ default .Values.config.keycloak.dataEgress.api.host .Values.config.keycloak.global.host }}/realms/{{ .Values.config.keycloak.dataEgress.api.realm }}"
            - name: DataEgressKeyCloakSettings__ClientId
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.keycloak.dataEgress.api.secretName }}
                  key: {{ .Values.config.keycloak.dataEgress.api.clientIdKey }}
            - name: DataEgressKeyCloakSettings__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.keycloak.dataEgress.api.secretName }}
                  key: {{ .Values.config.keycloak.dataEgress.api.clientSecretKey }}
            - name: DataEgressKeyCloakSettings__ValidAudience
              value: "{{ .Values.config.keycloak.dataEgress.api.validAudiences }}"
            - name: DataEgressKeyCloakSettings__Proxy
              value: "{{ .Values.config.keycloak.proxy.enabled }}"
            - name: DataEgressKeyCloakSettings__ProxyAddresURL
              value: "{{ .Values.config.keycloak.proxy.url }}"
            - name: DataEgressKeyCloakSettings__BypassProxy
              value: "{{ .Values.config.keycloak.proxy.bypassList }}"
            - name: DataEgressKeyCloakSettings__UseRedirectURL
              value: "{{ .Values.config.keycloak.dataEgress.api.useRedirect }}"
            - name: DataEgressKeyCloakSettings__RedirectURL
              value: "{{ .Values.config.keycloak.dataEgress.ui.redirectUrl }}" 
            - name: sslcookies
              value: "{{ .Values.config.sslCookies }}"
            - name: httpsRedirect
              value: "{{ .Values.config.httpsRedirect }}"
            - name: DataEgressKeyCloakSettings__AccountManagementURL
              value: "{{ default .Values.config.keycloak.dataEgress.api.protocol .Values.config.keycloak.global.protocol }}://{{ default .Values.config.keycloak.dataEgress.api.host .Values.config.keycloak.global.host }}/realms/{{ .Values.config.keycloak.dataEgress.api.realm }}/account"
            - name: Helpdesk__URL
              value: "{{ .Values.config.helpdeskUrl }}"
            - name: MinioSettings__Url
              value: "{{ .Values.config.minio.tre.url }}"
            {{- with .Values.dataEgress.ui.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.dataEgress.ui.service.port }}
              protocol: TCP
          {{- with .Values.dataEgress.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataEgress.ui.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.dataEgress.ui.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
