uiVersion: v1
kind: Service
metadata:
  name: {{ include "tre.fullname" . }}-data-egress-ui
  labels:
    {{- include "tre.labels" . | nindent 4 }}
    component: "data-egress-ui"
spec:
  type: {{ .Values.dataEgress.ui.service.type }}
  ports:
    - port: {{ .Values.dataEgress.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tre.selectorLabels" . | nindent 4 }}
    component: "data-egress-ui"
